# Software

I have a keen interest in software development with regard to forest inventory systems.
I am currently developing and maintaining several packages for use in forest resource
analysis.

All of these packages are open source and free to use. If you are interested in
collaborating please to do not hesitate to reach me at any one of these 
[contacts](contact).

[pyfor](https://github.com/brycefrank/PyFor): A LiDAR processing package written
in the Python programming language.

[forvol](https://github.com/brycefrank/forvol): A tree volume equation library
written in the R programming language. forvol provides a flexible way for forest
inventory professionals to interact with FIA volume equations for various species. 
This package is operable for many Pacific Northwest tree species, but still needs 
a lot of work in terms of adding volume equations and automated testing.

[laxpy](https://github/com/brycefrank/laxpy): This small package allows Python
users to access the spatial indexing (`.lax`) files generated by [LASlib](https://github.com/LAStools/LAStools/tree/master/LASlib).
This makes clipping `.las` files much more memory efficient.
